################################# Default configuration ###################
# provide your domain here
baseURL = "https://wiki.foss-planet.de"
# theme
theme = "dot"
# site title
title = "FOSS Planet - Wiki"
# disable language
disableLanguages = []

defaultContentLanguage = "de"

# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = "/images/logo.png"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#031929"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "Fira Sans" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "fab fa-google" # themify icon pack : https://themify.me/themify-icons
link = "https://news.google.com/publications/CAAqBwgKMOu2oQswg8G5Aw?oc=3&ceid=DE:de"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/fossplanet"

[[params.social]]
icon = "fab fa-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/lxdb-team/fossplanet-wiki"

[[params.social]]
icon = "fab fa-telegram" # themify icon pack : https://themify.me/themify-icons
link = "https://t.me/fossplanet"

[[params.social]]
icon = "fab fa-flipboard" # themify icon pack : https://themify.me/themify-icons
link = "https://flipboard.com/@fossplanet/foss-planet-ngdmpullz?from=share&utm_source=flipboard&utm_medium=share"


################################### Franch Language ######################
[Languages.de]
languageName = "De"
languageCode = "de-de"
weight = 2
copyright = "Copyright © 2021 [LXDB Team](https://www.lxdb.de)"

# banner
[Languages.de.params.banner]
title = "FOSS Planet"
subtitle = "Das deutsche FOSS Wiki"
bg_image = "images/banner.png"
placeholder = "Suchen..."

# call to action
[Languages.de.params.cta]
enable = true
title = "Offene Fragen?"
content = "Du hast eine Frage die das Wiki nicht beantworten kann? Stelle sie der Community auf unserem Discord-Server!"
# call to action button
[Languages.de.params.cta.button]
enable = true
label = "Server beitreten"
link = "https://discord.gg/sf382PBWpX"


################## french navigation #################
[[Languages.de.menu.main]]
name = "Start"
url = "/"
weight = 1

[[Languages.de.menu.main]]
name = "Faq"
url = "faq"
weight = 2

[[Languages.de.menu.main]]
name = "Kontakt"
url = "contact"
weight = 3

# Dropdown menu
[[Languages.de.menu.main]]
weight = 4
name = "Wiki"
hasChildren = true

  [[Languages.de.menu.main]]
  parent = "Wiki"
  name = "LXDB Software"
  url = "lxdb-software"
  weight = 1

  [[Languages.de.menu.main]]
  parent = "Wiki"
  name = "Linux-Distributionen"
  url = "linux"
  weight = 2

  [[Languages.de.menu.main]]
  parent = "Wiki"
  name = "Programme"
  url = "programs"
  weight = 3
